AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smithy4s-sandbox

  Sample SAM Template for smithy4s-sandbox
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  InsertDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/insert-dynamodb/target/scala-3.5.2/npm-package/
      Handler: index.Handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref Smithy4sSandboxTable
  Smithy4sSandboxTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Smithy4sSandboxTable
